### ISSUE TITLE
更新到3.0.1后切歌闪退

### ISSUE THREAD

**Issue by ston-afk** [anhoder/go-musicfox#27]
闪退后终端输出如下
```
net/http.(*persistConn).Read(0xc0004d4120, {0xc0005ae000?, 0xc000213b50?, 0x100000000429fc5?})
	/usr/local/go/src/net/http/transport.go:1929 +0x4e
bufio.(*Reader).Read(0xc00030ecc0, {0xc0005ae000, 0x8000, 0x466e5b?})
	/usr/local/go/src/bufio/bufio.go:222 +0x106
io.(*LimitedReader).Read(0xc00056e948, {0xc0005ae000?, 0xc000213c00?, 0x4b52fb?})
	/usr/local/go/src/io/io.go:476 +0x45
net/http.(*body).readLocked(0xc0006160c0, {0xc0005ae000?, 0x4d04e6?, 0xc000682ba0?})
	/usr/local/go/src/net/http/transfer.go:844 +0x3c
net/http.(*body).Read(0xc000646118?, {0xc0005ae000?, 0xc0003462a0?, 0xc000682bb8?})
	/usr/local/go/src/net/http/transfer.go:836 +0x125
net/http.(*bodyEOFSignal).Read(0xc000616100, {0xc0005ae000, 0x8000, 0x8000})
	/usr/local/go/src/net/http/transport.go:2774 +0x142
go-musicfox/utils.Copy.func1({0xc0005ae000, 0x8000, 0x8000})
	/go/src/go-musicfox/utils/io_copy.go:21 +0xa5
go-musicfox/utils.readerFunc.Read(0x10?, {0xc0005ae000?, 0xc0003822b0?, 0xc000300000?})
	/go/src/go-musicfox/utils/io_copy.go:11 +0x2a
io.copyBuffer({0xacb3a0, 0xc0003822b0}, {0xacac80, 0xc0001783f0}, {0x0, 0x0, 0x0})
	/usr/local/go/src/io/io.go:426 +0x1b2
io.Copy(...)
	/usr/local/go/src/io/io.go:385
os.genericReadFrom(0x0?, {0xacac80, 0xc0001783f0})
	/usr/local/go/src/os/file.go:162 +0x67
os.(*File).ReadFrom(0xc000330050, {0xacac80, 0xc0001783f0})
	/usr/local/go/src/os/file.go:156 +0x1b0
io.copyBuffer({0xaca5a0, 0xc000330050}, {0xacac80, 0xc0001783f0}, {0x0, 0x0, 0x0})
	/usr/local/go/src/io/io.go:412 +0x14b
io.Copy(...)
	/usr/local/go/src/io/io.go:385
go-musicfox/utils.Copy({0xacdd88?, 0xc000646100?}, {0xaca5a0?, 0xc000330050?}, {0xaca2a0?, 0xc000616100?})
	/go/src/go-musicfox/utils/io_copy.go:16 +0xd7
go-musicfox/pkg/player.(*beepPlayer).listen.func1({0xacdd88, 0xc000646100}, 0xc00029dfd0?, {0xacc800?, 0xc000616100})
	/go/src/go-musicfox/pkg/player/beep_player.go:141 +0x88
created by go-musicfox/pkg/player.(*beepPlayer).listen
	/go/src/go-musicfox/pkg/player/beep_player.go:139 +0x45b

goroutine 147 [chan receive]:
github.com/tosone/minimp3.(*Decoder).Started.func1()
	/go/src/go-musicfox/vendor/github.com/tosone/minimp3/decode.go:135 +0x45
created by github.com/tosone/minimp3.(*Decoder).Started
	/go/src/go-musicfox/vendor/github.com/tosone/minimp3/decode.go:123 +0xad

rax    0x0
rbx    0x2fc0
rcx    0x7f2becca849c
rdx    0x6
rdi    0x2fad
rsi    0x2fc0
rbp    0x7f2b967fc6c0
rsp    0x7f2b967fbac0
r8     0xffffffff
r9     0x0
r10    0x8
r11    0x246
r12    0x6
r13    0x7f2bc4153000
r14    0x1
r15    0x1
rip    0x7f2becca849c
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```

**Comment by anhoder** [comment]
看下`~/.go-musicfox/musicfox.log`有没有日志，贴下呗，linux吗

**Comment by ston-afk** [comment]
```
2022/09/26 11:53:10 [ERROR] Lastfm other err: empty session key
go-musicfox/pkg/lastfm.(*Client).UpdateNowPlaying
	/go/src/go-musicfox/pkg/lastfm/api.go:82
go-musicfox/pkg/ui.(*Player).report.func1
	/go/src/go-musicfox/pkg/ui/player.go:737
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1571
2022/09/26 11:53:27 [ERROR] Lastfm other err: empty session key
go-musicfox/pkg/lastfm.(*Client).UpdateNowPlaying
	/go/src/go-musicfox/pkg/lastfm/api.go:82
go-musicfox/pkg/ui.(*Player).report.func1
	/go/src/go-musicfox/pkg/ui/player.go:737
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1571
```

**Comment by ston-afk** [comment]
是Linux

**Comment by ston-afk** [comment]
之前没这个问题的，更新到3.0.1后出现的bug

**Comment by anhoder** [comment]
> 系统是Arch Linux
> 
> ```
> 2022/09/26 11:53:10 [ERROR] Lastfm other err: empty session key
> go-musicfox/pkg/lastfm.(*Client).UpdateNowPlaying
> 	/go/src/go-musicfox/pkg/lastfm/api.go:82
> go-musicfox/pkg/ui.(*Player).report.func1
> 	/go/src/go-musicfox/pkg/ui/player.go:737
> runtime.goexit
> 	/usr/local/go/src/runtime/asm_amd64.s:1571
> 2022/09/26 11:53:27 [ERROR] Lastfm other err: empty session key
> go-musicfox/pkg/lastfm.(*Client).UpdateNowPlaying
> 	/go/src/go-musicfox/pkg/lastfm/api.go:82
> go-musicfox/pkg/ui.(*Player).report.func1
> 	/go/src/go-musicfox/pkg/ui/player.go:737
> runtime.goexit
> 	/usr/local/go/src/runtime/asm_amd64.s:1571
> ```

不是这个，这个是lastfm正常的日志，没有其他日志内容了吗，这个报错能稳定复现不

**Comment by anhoder** [comment]
我的Mac和Windows复现不了，你可以把配置文件的altScreen改成false，下次运行报错时就能拿到完整的报错信息了

**Comment by ston-afk** [comment]
```
double free or corruption (out)                          00:00/03:20
SIGABRT: abort
PC=0x7f6a1e78649c m=11 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 158 [syscall]:
runtime.cgocall(0x8d07e0, 0xc000285e90)
	/usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc000285e68 sp=0xc000285e30 pc=0x406fbc
github.com/hajimehoshi/oto._Cfunc_snd_pcm_close(0x7f69d805f200)
	_cgo_gotypes.go:121 +0x4c fp=0xc000285e90 sp=0xc000285e68 pc=0x87e0ac
github.com/hajimehoshi/oto.(*driver).Close.func2(0xc00009e910?)
	/go/src/go-musicfox/vendor/github.com/hajimehoshi/oto/driver_linux.go:179 +0x46 fp=0xc000285ec8 sp=0xc000285e90 pc=0x87f346
github.com/hajimehoshi/oto.(*driver).Close(0xbebc200?)
	/go/src/go-musicfox/vendor/github.com/hajimehoshi/oto/driver_linux.go:179 +0x2e fp=0xc000285ee8 sp=0xc000285ec8 pc=0x87f2ae
github.com/hajimehoshi/oto.(*driverWriter).Close(0xc0001fe9f0)
	/go/src/go-musicfox/vendor/github.com/hajimehoshi/oto/context.go:170 +0xc9 fp=0xc000285f38 sp=0xc000285ee8 pc=0x87d7c9
github.com/hajimehoshi/oto.(*Context).Close(0xc000279350)
	/go/src/go-musicfox/vendor/github.com/hajimehoshi/oto/context.go:106 +0xa5 fp=0xc000285f80 sp=0xc000285f38 pc=0x87d245
github.com/hajimehoshi/oto.NewContext.func1()
	/go/src/go-musicfox/vendor/github.com/hajimehoshi/oto/context.go:89 +0x8f fp=0xc000285fe0 sp=0xc000285f80 pc=0x87d0cf
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000285fe8 sp=0xc000285fe0 pc=0x46be01
created by github.com/hajimehoshi/oto.NewContext
	/go/src/go-musicfox/vendor/github.com/hajimehoshi/oto/context.go:84 +0x2af

goroutine 1 [select]:
github.com/anhoder/bubbletea.(*Program).Start(0xc0001bbe30)
	/go/src/go-musicfox/vendor/github.com/anhoder/bubbletea/tea.go:348 +0x911
go-musicfox/pkg/commands.runPlayer(0xc0001fc0c0?, {0xc0001fa160?, 0x0?, 0x0?})
	/go/src/go-musicfox/pkg/commands/netease.go:41 +0xf5
github.com/gookit/gcli/v2.(*Command).execute(0xc0001fc000, {0xc0001fa160, 0x0, 0x0})
	/go/src/go-musicfox/vendor/github.com/gookit/gcli/v2/cmd.go:243 +0x104
github.com/gookit/gcli/v2.(*App).doRun(0xc0000e86e0, {0x9cef0f, 0x7}, {0xc0001fa160, 0x0, 0x0})
	/go/src/go-musicfox/vendor/github.com/gookit/gcli/v2/app_run.go:173 +0x429
github.com/gookit/gcli/v2.(*App).Run(0xc0000e86e0)
	/go/src/go-musicfox/vendor/github.com/gookit/gcli/v2/app_run.go:126 +0x2ee
go-musicfox/pkg/entry.runCLI()
	/go/src/go-musicfox/pkg/entry/cli.go:35 +0x23c
go-musicfox/pkg/entry.AppEntry()
	/go/src/go-musicfox/pkg/entry/entry.go:11 +0x3b
main.main()
	/go/src/go-musicfox/cmd/musicfox.go:6 +0x17

goroutine 6 [chan receive]:
github.com/faiface/beep/minimp3.Decode({0xacccd8?, 0xc00034e000})
	/go/src/go-musicfox/vendor/github.com/faiface/beep/minimp3/decode.go:22 +0xda
go-musicfox/pkg/player.(*beepPlayer).listen(0xc0000e7200)
	/go/src/go-musicfox/pkg/player/beep_player.go:157 +0x4ac
go-musicfox/pkg/player.NewBeepPlayer.func1()
	/go/src/go-musicfox/pkg/player/beep_player.go:62 +0x3f
created by go-musicfox/pkg/player.NewBeepPlayer
	/go/src/go-musicfox/pkg/player/beep_player.go:60 +0x216

goroutine 7 [chan receive]:
go-musicfox/pkg/ui.NewPlayer.func1()
	/go/src/go-musicfox/pkg/ui/player.go:110 +0x9e
created by go-musicfox/pkg/ui.NewPlayer
	/go/src/go-musicfox/pkg/ui/player.go:108 +0x11c

goroutine 8 [chan receive]:
go-musicfox/pkg/ui.NewPlayer.func2()
	/go/src/go-musicfox/pkg/ui/player.go:143 +0x97
created by go-musicfox/pkg/ui.NewPlayer
	/go/src/go-musicfox/pkg/ui/player.go:141 +0x159

goroutine 9 [chan receive]:
go-musicfox/pkg/ui.NewPlayer.func3()
	/go/src/go-musicfox/pkg/ui/player.go:168 +0x9f
created by go-musicfox/pkg/ui.NewPlayer
	/go/src/go-musicfox/pkg/ui/player.go:166 +0x196

goroutine 10 [select]:
github.com/anhoder/bubbletea.(*Program).Start.func1()
	/go/src/go-musicfox/vendor/github.com/anhoder/bubbletea/tea.go:255 +0x12d
created by github.com/anhoder/bubbletea.(*Program).Start
	/go/src/go-musicfox/vendor/github.com/anhoder/bubbletea/tea.go:250 +0x32c

goroutine 71 [IO wait]:
internal/poll.runtime_pollWait(0x7f69f702ebd8, 0x72)
	/usr/local/go/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc000038a00?, 0xc00022b000?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc000038a00, {0xc00022b000, 0xe61, 0xe61})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc000038a00, {0xc00022b000?, 0x95ed01?, 0xc000592940?})
	/usr/local/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc000010508, {0xc00022b000?, 0x381?, 0xc000592940?})
	/usr/local/go/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc00000e240, {0xc00022b000?, 0x0?, 0x144?})
	/usr/local/go/src/crypto/tls/conn.go:784 +0x3d
bytes.(*Buffer).ReadFrom(0xc00012e278, {0xac95c0, 0xc00000e240})
	/usr/local/go/src/bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc00012e000, {0xaca1c0?, 0xc000010508}, 0xc00022bae5?)
	/usr/local/go/src/crypto/tls/conn.go:806 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc00012e000, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:613 +0x116
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:581
crypto/tls.(*Conn).Read(0xc00012e000, {0xc0001e9000, 0x1000, 0x6d9f40?})
	/usr/local/go/src/crypto/tls/conn.go:1284 +0x16f
bufio.(*Reader).Read(0xc0005da600, {0xc000573540, 0x9, 0x6f6902?})
	/usr/local/go/src/bufio/bufio.go:236 +0x1b4
io.ReadAtLeast({0xac9440, 0xc0005da600}, {0xc000573540, 0x9, 0x9}, 0x9)
	/usr/local/go/src/io/io.go:331 +0x9a
io.ReadFull(...)
	/usr/local/go/src/io/io.go:350
net/http.http2readFrameHeader({0xc000573540?, 0x9?, 0xc00056e1b0?}, {0xac9440?, 0xc0005da600?})
	/usr/local/go/src/net/http/h2_bundle.go:1566 +0x6e
net/http.(*http2Framer).ReadFrame(0xc000573500)
	/usr/local/go/src/net/http/h2_bundle.go:1830 +0x95
net/http.(*http2clientConnReadLoop).run(0xc000286f98)
	/usr/local/go/src/net/http/h2_bundle.go:8815 +0x130
net/http.(*http2ClientConn).readLoop(0xc00012c180)
	/usr/local/go/src/net/http/h2_bundle.go:8711 +0x6f
created by net/http.(*http2Transport).newClientConn
	/usr/local/go/src/net/http/h2_bundle.go:7439 +0xa65

goroutine 13 [syscall]:
syscall.Syscall(0x0, 0x0, 0xc000296100, 0x100)
	/usr/local/go/src/syscall/asm_linux_amd64.s:20 +0x5
syscall.read(0xc000094060?, {0xc000296100?, 0x0?, 0x7f69f4f8f108?})
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:696 +0x4d
syscall.Read(...)
	/usr/local/go/src/syscall/syscall_unix.go:188
internal/poll.ignoringEINTRIO(...)
	/usr/local/go/src/internal/poll/fd_unix.go:794
internal/poll.(*FD).Read(0xc000094060?, {0xc000296100?, 0x100?, 0x100?})
	/usr/local/go/src/internal/poll/fd_unix.go:163 +0x285
os.(*File).read(...)
	/usr/local/go/src/os/file_posix.go:31
os.(*File).Read(0xc000010010, {0xc000296100?, 0xc0002a80a8?, 0x2?})
	/usr/local/go/src/os/file.go:119 +0x5e
github.com/anhoder/bubbletea.readInput({0xaca580, 0xc000010010})
	/go/src/go-musicfox/vendor/github.com/anhoder/bubbletea/key.go:286 +0x71
github.com/anhoder/bubbletea.(*Program).Start.func4()
	/go/src/go-musicfox/vendor/github.com/anhoder/bubbletea/tea.go:303 +0x6c
created by github.com/anhoder/bubbletea.(*Program).Start
	/go/src/go-musicfox/vendor/github.com/anhoder/bubbletea/tea.go:301 +0x63b

goroutine 202 [select]:
go-musicfox/pkg/lyric.(*LRCTimer).Start(0xc000396080)
	/go/src/go-musicfox/pkg/lyric/lrc_timer.go:46 +0x148
go-musicfox/pkg/ui.(*Player).updateLyric.func1()
	/go/src/go-musicfox/pkg/ui/player.go:628 +0x176
go-musicfox/pkg/ui.(*Player).updateLyric(0xc0000b7860, 0xe45818?)
	/go/src/go-musicfox/pkg/ui/player.go:644 +0x29c
created by go-musicfox/pkg/ui.(*Player).PlaySong
	/go/src/go-musicfox/pkg/ui/player.go:437 +0x5c9

goroutine 15 [chan receive]:
github.com/anhoder/bubbletea.listenForResize(0xc000010018, 0x0?, 0x0?)
	/go/src/go-musicfox/vendor/github.com/anhoder/bubbletea/signals_unix.go:20 +0xd1
created by github.com/anhoder/bubbletea.(*Program).Start
	/go/src/go-musicfox/vendor/github.com/anhoder/bubbletea/tea.go:327 +0x73c

goroutine 16 [select]:
github.com/anhoder/bubbletea.(*Program).Start.func6()
	/go/src/go-musicfox/vendor/github.com/anhoder/bubbletea/tea.go:333 +0x94
created by github.com/anhoder/bubbletea.(*Program).Start
	/go/src/go-musicfox/vendor/github.com/anhoder/bubbletea/tea.go:331 +0x7bb

goroutine 19 [syscall]:
os/signal.signal_recv()
	/usr/local/go/src/runtime/sigqueue.go:151 +0x2f
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x19
created by os/signal.Notify.func1.1
	/usr/local/go/src/os/signal/signal.go:151 +0x2a

goroutine 245 [chan receive]:
github.com/tosone/minimp3.(*Decoder).Started.func1()
	/go/src/go-musicfox/vendor/github.com/tosone/minimp3/decode.go:135 +0x45
created by github.com/tosone/minimp3.(*Decoder).Started
	/go/src/go-musicfox/vendor/github.com/tosone/minimp3/decode.go:123 +0xad

goroutine 216 [IO wait]:
internal/poll.runtime_pollWait(0x7f69f702eae8, 0x72)
	/usr/local/go/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc000350200?, 0xc00037a000?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc000350200, {0xc00037a000, 0x104c, 0x104c})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc000350200, {0xc00037a000?, 0xc00034a460?, 0xc00037a61c?})
	/usr/local/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc00034e068, {0xc00037a000?, 0x82?, 0xc0000bf818?})
	/usr/local/go/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc000742108, {0xc00037a000?, 0x0?, 0x86?})
	/usr/local/go/src/crypto/tls/conn.go:784 +0x3d
bytes.(*Buffer).ReadFrom(0xc00012e5f8, {0xac95c0, 0xc000742108})
	/usr/local/go/src/bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc00012e380, {0xaca1c0?, 0xc00034e068}, 0xa35?)
	/usr/local/go/src/crypto/tls/conn.go:806 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc00012e380, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:613 +0x116
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:581
crypto/tls.(*Conn).Read(0xc00012e380, {0xc000487000, 0x1000, 0x6d9f40?})
	/usr/local/go/src/crypto/tls/conn.go:1284 +0x16f
bufio.(*Reader).Read(0xc000288b40, {0xc000572200, 0x9, 0x6f6902?})
	/usr/local/go/src/bufio/bufio.go:236 +0x1b4
io.ReadAtLeast({0xac9440, 0xc000288b40}, {0xc000572200, 0x9, 0x9}, 0x9)
	/usr/local/go/src/io/io.go:331 +0x9a
io.ReadFull(...)
	/usr/local/go/src/io/io.go:350
net/http.http2readFrameHeader({0xc000572200?, 0x9?, 0xc0003fe1e0?}, {0xac9440?, 0xc000288b40?})
	/usr/local/go/src/net/http/h2_bundle.go:1566 +0x6e
net/http.(*http2Framer).ReadFrame(0xc0005721c0)
	/usr/local/go/src/net/http/h2_bundle.go:1830 +0x95
net/http.(*http2clientConnReadLoop).run(0xc0000bff98)
	/usr/local/go/src/net/http/h2_bundle.go:8815 +0x130
net/http.(*http2ClientConn).readLoop(0xc00012c480)
	/usr/local/go/src/net/http/h2_bundle.go:8711 +0x6f
created by net/http.(*http2Transport).newClientConn
	/usr/local/go/src/net/http/h2_bundle.go:7439 +0xa65

goroutine 243 [IO wait]:
internal/poll.runtime_pollWait(0x7f69f702e9f8, 0x72)
	/usr/local/go/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc000350180?, 0xc0005f8000?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc000350180, {0xc0005f8000, 0x8000, 0x8000})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc000350180, {0xc0005f8000?, 0x0?, 0x0?})
	/usr/local/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc00034e038, {0xc0005f8000?, 0x0?, 0xc000287b18?})
	/usr/local/go/src/net/net.go:183 +0x45
net/http.(*persistConn).Read(0xc0000e65a0, {0xc0005f8000?, 0xc000287b50?, 0x100000000429fc5?})
	/usr/local/go/src/net/http/transport.go:1929 +0x4e
bufio.(*Reader).Read(0xc000574a20, {0xc0005f8000, 0x8000, 0x466e5b?})
	/usr/local/go/src/bufio/bufio.go:222 +0x106
io.(*LimitedReader).Read(0xc000559f38, {0xc0005f8000?, 0xc000287c00?, 0x4b52fb?})
	/usr/local/go/src/io/io.go:476 +0x45
net/http.(*body).readLocked(0xc0003960c0, {0xc0005f8000?, 0x4d04e6?, 0xc000574540?})
	/usr/local/go/src/net/http/transfer.go:844 +0x3c
net/http.(*body).Read(0xc0004d2018?, {0xc0005f8000?, 0xc0000a0360?, 0xc000574558?})
	/usr/local/go/src/net/http/transfer.go:836 +0x125
net/http.(*bodyEOFSignal).Read(0xc000396140, {0xc0005f8000, 0x8000, 0x8000})
	/usr/local/go/src/net/http/transport.go:2774 +0x142
go-musicfox/utils.Copy.func1({0xc0005f8000, 0x8000, 0x8000})
	/go/src/go-musicfox/utils/io_copy.go:21 +0xa5
go-musicfox/utils.readerFunc.Read(0x10?, {0xc0005f8000?, 0xc00034ca50?, 0xc000303000?})
	/go/src/go-musicfox/utils/io_copy.go:11 +0x2a
io.copyBuffer({0xacb3a0, 0xc00034ca50}, {0xacac80, 0xc0004c21b0}, {0x0, 0x0, 0x0})
	/usr/local/go/src/io/io.go:426 +0x1b2
io.Copy(...)
	/usr/local/go/src/io/io.go:385
os.genericReadFrom(0x0?, {0xacac80, 0xc0004c21b0})
	/usr/local/go/src/os/file.go:162 +0x67
os.(*File).ReadFrom(0xc00034e008, {0xacac80, 0xc0004c21b0})
	/usr/local/go/src/os/file.go:156 +0x1b0
io.copyBuffer({0xaca5a0, 0xc00034e008}, {0xacac80, 0xc0004c21b0}, {0x0, 0x0, 0x0})
	/usr/local/go/src/io/io.go:412 +0x14b
io.Copy(...)
	/usr/local/go/src/io/io.go:385
go-musicfox/utils.Copy({0xacdd88?, 0xc0004d2000?}, {0xaca5a0?, 0xc00034e008?}, {0xaca2a0?, 0xc000396140?})
	/go/src/go-musicfox/utils/io_copy.go:16 +0xd7
go-musicfox/pkg/player.(*beepPlayer).listen.func1({0xacdd88, 0xc0004d2000}, 0xc0004e08c8?, {0xacc800?, 0xc000396140})
	/go/src/go-musicfox/pkg/player/beep_player.go:141 +0x88
created by go-musicfox/pkg/player.(*beepPlayer).listen
	/go/src/go-musicfox/pkg/player/beep_player.go:139 +0x45b

goroutine 244 [chan receive]:
github.com/tosone/minimp3.NewDecoder.func1()
	/go/src/go-musicfox/vendor/github.com/tosone/minimp3/decode.go:73 +0xa9
created by github.com/tosone/minimp3.NewDecoder
	/go/src/go-musicfox/vendor/github.com/tosone/minimp3/decode.go:65 +0x1f8

goroutine 207 [select]:
net/http.(*persistConn).readLoop(0xc0000e65a0)
	/usr/local/go/src/net/http/transport.go:2213 +0xda5
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1750 +0x173e

goroutine 208 [select]:
net/http.(*persistConn).writeLoop(0xc0000e65a0)
	/usr/local/go/src/net/http/transport.go:2392 +0xf5
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1751 +0x1791

rax    0x0
rbx    0x4915
rcx    0x7f6a1e78649c
rdx    0x6
rdi    0x490a
rsi    0x4915
rbp    0x7f69de7fc6c0
rsp    0x7f69de7fbac0
r8     0xffffffff
r9     0x0
r10    0x8
r11    0x246
r12    0x6
r13    0x7f69f4466000
r14    0x1
r15    0x1
rip    0x7f6a1e78649c
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```

**Comment by anhoder** [comment]
发了个v3.0.2，你可以升级试一下，不一定有效

**Comment by ston-afk** [comment]
升级完后不再闪退，是有效的
